namespace RAJANI_ERP
{
    partial class MainPage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuButtonStock = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonSettings = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonInvoices = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonProducts = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonCompany = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuButtonDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(17)))), ((int)(((byte)(23)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuButtonStock);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonSettings);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonInvoices);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonProducts);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonCustomer);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonCompany);
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Controls.Add(this.bunifuButtonDashboard);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Font = new System.Drawing.Font("Rockwell Condensed", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(225, 661);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // bunifuButtonStock
            // 
            this.bunifuButtonStock.AllowAnimations = true;
            this.bunifuButtonStock.AllowMouseEffects = true;
            this.bunifuButtonStock.AllowToggling = false;
            this.bunifuButtonStock.AnimationSpeed = 200;
            this.bunifuButtonStock.AutoGenerateColors = false;
            this.bunifuButtonStock.AutoRoundBorders = false;
            this.bunifuButtonStock.AutoSizeLeftIcon = true;
            this.bunifuButtonStock.AutoSizeRightIcon = true;
            this.bunifuButtonStock.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonStock.BackgroundImage")));
            this.bunifuButtonStock.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonStock.ButtonText = "Stock";
            this.bunifuButtonStock.ButtonTextMarginLeft = 0;
            this.bunifuButtonStock.ColorContrastOnClick = 45;
            this.bunifuButtonStock.ColorContrastOnHover = 45;
            this.bunifuButtonStock.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonStock.CustomizableEdges = borderEdges1;
            this.bunifuButtonStock.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonStock.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonStock.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonStock.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonStock.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonStock.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonStock.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonStock.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonStock.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonStock.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonStock.IconMarginLeft = 11;
            this.bunifuButtonStock.IconPadding = 5;
            this.bunifuButtonStock.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonStock.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonStock.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonStock.IconSize = 30;
            this.bunifuButtonStock.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.IdleBorderRadius = 1;
            this.bunifuButtonStock.IdleBorderThickness = 1;
            this.bunifuButtonStock.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonStock.IdleIconLeftImage")));
            this.bunifuButtonStock.IdleIconRightImage = null;
            this.bunifuButtonStock.IndicateFocus = false;
            this.bunifuButtonStock.Location = new System.Drawing.Point(5, 300);
            this.bunifuButtonStock.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonStock.Name = "bunifuButtonStock";
            this.bunifuButtonStock.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonStock.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonStock.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonStock.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonStock.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonStock.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonStock.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonStock.OnDisabledState.IconRightImage = null;
            this.bunifuButtonStock.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonStock.onHoverState.BorderRadius = 1;
            this.bunifuButtonStock.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonStock.onHoverState.BorderThickness = 1;
            this.bunifuButtonStock.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonStock.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonStock.onHoverState.IconLeftImage = null;
            this.bunifuButtonStock.onHoverState.IconRightImage = null;
            this.bunifuButtonStock.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.OnIdleState.BorderRadius = 1;
            this.bunifuButtonStock.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonStock.OnIdleState.BorderThickness = 1;
            this.bunifuButtonStock.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonStock.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonStock.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonStock.OnIdleState.IconLeftImage")));
            this.bunifuButtonStock.OnIdleState.IconRightImage = null;
            this.bunifuButtonStock.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonStock.OnPressedState.BorderRadius = 1;
            this.bunifuButtonStock.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonStock.OnPressedState.BorderThickness = 1;
            this.bunifuButtonStock.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonStock.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonStock.OnPressedState.IconLeftImage = null;
            this.bunifuButtonStock.OnPressedState.IconRightImage = null;
            this.bunifuButtonStock.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonStock.TabIndex = 11;
            this.bunifuButtonStock.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonStock.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonStock.TextMarginLeft = 0;
            this.bunifuButtonStock.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonStock.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonSettings
            // 
            this.bunifuButtonSettings.AllowAnimations = true;
            this.bunifuButtonSettings.AllowMouseEffects = true;
            this.bunifuButtonSettings.AllowToggling = false;
            this.bunifuButtonSettings.AnimationSpeed = 200;
            this.bunifuButtonSettings.AutoGenerateColors = false;
            this.bunifuButtonSettings.AutoRoundBorders = false;
            this.bunifuButtonSettings.AutoSizeLeftIcon = true;
            this.bunifuButtonSettings.AutoSizeRightIcon = true;
            this.bunifuButtonSettings.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonSettings.BackgroundImage")));
            this.bunifuButtonSettings.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonSettings.ButtonText = "Settings";
            this.bunifuButtonSettings.ButtonTextMarginLeft = 0;
            this.bunifuButtonSettings.ColorContrastOnClick = 45;
            this.bunifuButtonSettings.ColorContrastOnHover = 45;
            this.bunifuButtonSettings.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonSettings.CustomizableEdges = borderEdges2;
            this.bunifuButtonSettings.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonSettings.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonSettings.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonSettings.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonSettings.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonSettings.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonSettings.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSettings.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonSettings.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonSettings.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonSettings.IconMarginLeft = 11;
            this.bunifuButtonSettings.IconPadding = 5;
            this.bunifuButtonSettings.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonSettings.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonSettings.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonSettings.IconSize = 30;
            this.bunifuButtonSettings.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.IdleBorderRadius = 1;
            this.bunifuButtonSettings.IdleBorderThickness = 1;
            this.bunifuButtonSettings.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonSettings.IdleIconLeftImage")));
            this.bunifuButtonSettings.IdleIconRightImage = null;
            this.bunifuButtonSettings.IndicateFocus = false;
            this.bunifuButtonSettings.Location = new System.Drawing.Point(5, 380);
            this.bunifuButtonSettings.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonSettings.Name = "bunifuButtonSettings";
            this.bunifuButtonSettings.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonSettings.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonSettings.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonSettings.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonSettings.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonSettings.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonSettings.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonSettings.OnDisabledState.IconRightImage = null;
            this.bunifuButtonSettings.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonSettings.onHoverState.BorderRadius = 1;
            this.bunifuButtonSettings.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonSettings.onHoverState.BorderThickness = 1;
            this.bunifuButtonSettings.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonSettings.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSettings.onHoverState.IconLeftImage = null;
            this.bunifuButtonSettings.onHoverState.IconRightImage = null;
            this.bunifuButtonSettings.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.OnIdleState.BorderRadius = 1;
            this.bunifuButtonSettings.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonSettings.OnIdleState.BorderThickness = 1;
            this.bunifuButtonSettings.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSettings.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSettings.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonSettings.OnIdleState.IconLeftImage")));
            this.bunifuButtonSettings.OnIdleState.IconRightImage = null;
            this.bunifuButtonSettings.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonSettings.OnPressedState.BorderRadius = 1;
            this.bunifuButtonSettings.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonSettings.OnPressedState.BorderThickness = 1;
            this.bunifuButtonSettings.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonSettings.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSettings.OnPressedState.IconLeftImage = null;
            this.bunifuButtonSettings.OnPressedState.IconRightImage = null;
            this.bunifuButtonSettings.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonSettings.TabIndex = 10;
            this.bunifuButtonSettings.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonSettings.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonSettings.TextMarginLeft = 0;
            this.bunifuButtonSettings.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonSettings.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonInvoices
            // 
            this.bunifuButtonInvoices.AllowAnimations = true;
            this.bunifuButtonInvoices.AllowMouseEffects = true;
            this.bunifuButtonInvoices.AllowToggling = false;
            this.bunifuButtonInvoices.AnimationSpeed = 200;
            this.bunifuButtonInvoices.AutoGenerateColors = false;
            this.bunifuButtonInvoices.AutoRoundBorders = false;
            this.bunifuButtonInvoices.AutoSizeLeftIcon = true;
            this.bunifuButtonInvoices.AutoSizeRightIcon = true;
            this.bunifuButtonInvoices.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonInvoices.BackgroundImage")));
            this.bunifuButtonInvoices.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonInvoices.ButtonText = "Invoices";
            this.bunifuButtonInvoices.ButtonTextMarginLeft = 0;
            this.bunifuButtonInvoices.ColorContrastOnClick = 45;
            this.bunifuButtonInvoices.ColorContrastOnHover = 45;
            this.bunifuButtonInvoices.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonInvoices.CustomizableEdges = borderEdges3;
            this.bunifuButtonInvoices.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonInvoices.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonInvoices.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonInvoices.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonInvoices.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonInvoices.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonInvoices.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonInvoices.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonInvoices.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonInvoices.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonInvoices.IconMarginLeft = 11;
            this.bunifuButtonInvoices.IconPadding = 5;
            this.bunifuButtonInvoices.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonInvoices.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonInvoices.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonInvoices.IconSize = 30;
            this.bunifuButtonInvoices.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.IdleBorderRadius = 1;
            this.bunifuButtonInvoices.IdleBorderThickness = 1;
            this.bunifuButtonInvoices.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonInvoices.IdleIconLeftImage")));
            this.bunifuButtonInvoices.IdleIconRightImage = null;
            this.bunifuButtonInvoices.IndicateFocus = false;
            this.bunifuButtonInvoices.Location = new System.Drawing.Point(5, 340);
            this.bunifuButtonInvoices.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonInvoices.Name = "bunifuButtonInvoices";
            this.bunifuButtonInvoices.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonInvoices.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonInvoices.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonInvoices.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonInvoices.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonInvoices.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonInvoices.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonInvoices.OnDisabledState.IconRightImage = null;
            this.bunifuButtonInvoices.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonInvoices.onHoverState.BorderRadius = 1;
            this.bunifuButtonInvoices.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonInvoices.onHoverState.BorderThickness = 1;
            this.bunifuButtonInvoices.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonInvoices.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonInvoices.onHoverState.IconLeftImage = null;
            this.bunifuButtonInvoices.onHoverState.IconRightImage = null;
            this.bunifuButtonInvoices.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.OnIdleState.BorderRadius = 1;
            this.bunifuButtonInvoices.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonInvoices.OnIdleState.BorderThickness = 1;
            this.bunifuButtonInvoices.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonInvoices.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonInvoices.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonInvoices.OnIdleState.IconLeftImage")));
            this.bunifuButtonInvoices.OnIdleState.IconRightImage = null;
            this.bunifuButtonInvoices.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonInvoices.OnPressedState.BorderRadius = 1;
            this.bunifuButtonInvoices.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonInvoices.OnPressedState.BorderThickness = 1;
            this.bunifuButtonInvoices.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonInvoices.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonInvoices.OnPressedState.IconLeftImage = null;
            this.bunifuButtonInvoices.OnPressedState.IconRightImage = null;
            this.bunifuButtonInvoices.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonInvoices.TabIndex = 9;
            this.bunifuButtonInvoices.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonInvoices.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonInvoices.TextMarginLeft = 0;
            this.bunifuButtonInvoices.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonInvoices.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonProducts
            // 
            this.bunifuButtonProducts.AllowAnimations = true;
            this.bunifuButtonProducts.AllowMouseEffects = true;
            this.bunifuButtonProducts.AllowToggling = false;
            this.bunifuButtonProducts.AnimationSpeed = 200;
            this.bunifuButtonProducts.AutoGenerateColors = false;
            this.bunifuButtonProducts.AutoRoundBorders = false;
            this.bunifuButtonProducts.AutoSizeLeftIcon = true;
            this.bunifuButtonProducts.AutoSizeRightIcon = true;
            this.bunifuButtonProducts.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonProducts.BackgroundImage")));
            this.bunifuButtonProducts.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonProducts.ButtonText = "Products";
            this.bunifuButtonProducts.ButtonTextMarginLeft = 0;
            this.bunifuButtonProducts.ColorContrastOnClick = 45;
            this.bunifuButtonProducts.ColorContrastOnHover = 45;
            this.bunifuButtonProducts.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButtonProducts.CustomizableEdges = borderEdges4;
            this.bunifuButtonProducts.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonProducts.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonProducts.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonProducts.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonProducts.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonProducts.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonProducts.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonProducts.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonProducts.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonProducts.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonProducts.IconMarginLeft = 11;
            this.bunifuButtonProducts.IconPadding = 5;
            this.bunifuButtonProducts.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonProducts.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonProducts.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonProducts.IconSize = 30;
            this.bunifuButtonProducts.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.IdleBorderRadius = 1;
            this.bunifuButtonProducts.IdleBorderThickness = 1;
            this.bunifuButtonProducts.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonProducts.IdleIconLeftImage")));
            this.bunifuButtonProducts.IdleIconRightImage = null;
            this.bunifuButtonProducts.IndicateFocus = false;
            this.bunifuButtonProducts.Location = new System.Drawing.Point(5, 260);
            this.bunifuButtonProducts.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonProducts.Name = "bunifuButtonProducts";
            this.bunifuButtonProducts.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonProducts.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonProducts.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonProducts.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonProducts.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonProducts.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonProducts.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonProducts.OnDisabledState.IconRightImage = null;
            this.bunifuButtonProducts.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonProducts.onHoverState.BorderRadius = 1;
            this.bunifuButtonProducts.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonProducts.onHoverState.BorderThickness = 1;
            this.bunifuButtonProducts.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonProducts.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonProducts.onHoverState.IconLeftImage = null;
            this.bunifuButtonProducts.onHoverState.IconRightImage = null;
            this.bunifuButtonProducts.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.OnIdleState.BorderRadius = 1;
            this.bunifuButtonProducts.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonProducts.OnIdleState.BorderThickness = 1;
            this.bunifuButtonProducts.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonProducts.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonProducts.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonProducts.OnIdleState.IconLeftImage")));
            this.bunifuButtonProducts.OnIdleState.IconRightImage = null;
            this.bunifuButtonProducts.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonProducts.OnPressedState.BorderRadius = 1;
            this.bunifuButtonProducts.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonProducts.OnPressedState.BorderThickness = 1;
            this.bunifuButtonProducts.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonProducts.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonProducts.OnPressedState.IconLeftImage = null;
            this.bunifuButtonProducts.OnPressedState.IconRightImage = null;
            this.bunifuButtonProducts.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonProducts.TabIndex = 7;
            this.bunifuButtonProducts.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonProducts.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonProducts.TextMarginLeft = 0;
            this.bunifuButtonProducts.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonProducts.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonCustomer
            // 
            this.bunifuButtonCustomer.AllowAnimations = true;
            this.bunifuButtonCustomer.AllowMouseEffects = true;
            this.bunifuButtonCustomer.AllowToggling = false;
            this.bunifuButtonCustomer.AnimationSpeed = 200;
            this.bunifuButtonCustomer.AutoGenerateColors = false;
            this.bunifuButtonCustomer.AutoRoundBorders = false;
            this.bunifuButtonCustomer.AutoSizeLeftIcon = true;
            this.bunifuButtonCustomer.AutoSizeRightIcon = true;
            this.bunifuButtonCustomer.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCustomer.BackgroundImage")));
            this.bunifuButtonCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCustomer.ButtonText = "Customer";
            this.bunifuButtonCustomer.ButtonTextMarginLeft = 0;
            this.bunifuButtonCustomer.ColorContrastOnClick = 45;
            this.bunifuButtonCustomer.ColorContrastOnHover = 45;
            this.bunifuButtonCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButtonCustomer.CustomizableEdges = borderEdges5;
            this.bunifuButtonCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonCustomer.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonCustomer.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCustomer.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonCustomer.IconMarginLeft = 11;
            this.bunifuButtonCustomer.IconPadding = 5;
            this.bunifuButtonCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCustomer.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonCustomer.IconSize = 30;
            this.bunifuButtonCustomer.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.IdleBorderRadius = 1;
            this.bunifuButtonCustomer.IdleBorderThickness = 1;
            this.bunifuButtonCustomer.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCustomer.IdleIconLeftImage")));
            this.bunifuButtonCustomer.IdleIconRightImage = null;
            this.bunifuButtonCustomer.IndicateFocus = false;
            this.bunifuButtonCustomer.Location = new System.Drawing.Point(5, 220);
            this.bunifuButtonCustomer.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonCustomer.Name = "bunifuButtonCustomer";
            this.bunifuButtonCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCustomer.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCustomer.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCustomer.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonCustomer.OnDisabledState.IconRightImage = null;
            this.bunifuButtonCustomer.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonCustomer.onHoverState.BorderRadius = 1;
            this.bunifuButtonCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCustomer.onHoverState.BorderThickness = 1;
            this.bunifuButtonCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCustomer.onHoverState.IconLeftImage = null;
            this.bunifuButtonCustomer.onHoverState.IconRightImage = null;
            this.bunifuButtonCustomer.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.OnIdleState.BorderRadius = 1;
            this.bunifuButtonCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCustomer.OnIdleState.BorderThickness = 1;
            this.bunifuButtonCustomer.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCustomer.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCustomer.OnIdleState.IconLeftImage")));
            this.bunifuButtonCustomer.OnIdleState.IconRightImage = null;
            this.bunifuButtonCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCustomer.OnPressedState.BorderRadius = 1;
            this.bunifuButtonCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCustomer.OnPressedState.BorderThickness = 1;
            this.bunifuButtonCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCustomer.OnPressedState.IconLeftImage = null;
            this.bunifuButtonCustomer.OnPressedState.IconRightImage = null;
            this.bunifuButtonCustomer.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonCustomer.TabIndex = 6;
            this.bunifuButtonCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonCustomer.TextMarginLeft = 0;
            this.bunifuButtonCustomer.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonCompany
            // 
            this.bunifuButtonCompany.AllowAnimations = true;
            this.bunifuButtonCompany.AllowMouseEffects = true;
            this.bunifuButtonCompany.AllowToggling = false;
            this.bunifuButtonCompany.AnimationSpeed = 200;
            this.bunifuButtonCompany.AutoGenerateColors = false;
            this.bunifuButtonCompany.AutoRoundBorders = false;
            this.bunifuButtonCompany.AutoSizeLeftIcon = true;
            this.bunifuButtonCompany.AutoSizeRightIcon = true;
            this.bunifuButtonCompany.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCompany.BackgroundImage")));
            this.bunifuButtonCompany.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCompany.ButtonText = "Company";
            this.bunifuButtonCompany.ButtonTextMarginLeft = 0;
            this.bunifuButtonCompany.ColorContrastOnClick = 45;
            this.bunifuButtonCompany.ColorContrastOnHover = 45;
            this.bunifuButtonCompany.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButtonCompany.CustomizableEdges = borderEdges6;
            this.bunifuButtonCompany.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonCompany.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCompany.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCompany.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCompany.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonCompany.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonCompany.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCompany.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonCompany.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCompany.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonCompany.IconMarginLeft = 11;
            this.bunifuButtonCompany.IconPadding = 5;
            this.bunifuButtonCompany.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonCompany.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCompany.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonCompany.IconSize = 30;
            this.bunifuButtonCompany.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.IdleBorderRadius = 1;
            this.bunifuButtonCompany.IdleBorderThickness = 1;
            this.bunifuButtonCompany.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCompany.IdleIconLeftImage")));
            this.bunifuButtonCompany.IdleIconRightImage = null;
            this.bunifuButtonCompany.IndicateFocus = false;
            this.bunifuButtonCompany.Location = new System.Drawing.Point(5, 180);
            this.bunifuButtonCompany.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonCompany.Name = "bunifuButtonCompany";
            this.bunifuButtonCompany.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCompany.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonCompany.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCompany.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonCompany.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCompany.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCompany.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonCompany.OnDisabledState.IconRightImage = null;
            this.bunifuButtonCompany.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonCompany.onHoverState.BorderRadius = 1;
            this.bunifuButtonCompany.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCompany.onHoverState.BorderThickness = 1;
            this.bunifuButtonCompany.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCompany.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCompany.onHoverState.IconLeftImage = null;
            this.bunifuButtonCompany.onHoverState.IconRightImage = null;
            this.bunifuButtonCompany.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.OnIdleState.BorderRadius = 1;
            this.bunifuButtonCompany.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCompany.OnIdleState.BorderThickness = 1;
            this.bunifuButtonCompany.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCompany.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCompany.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCompany.OnIdleState.IconLeftImage")));
            this.bunifuButtonCompany.OnIdleState.IconRightImage = null;
            this.bunifuButtonCompany.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCompany.OnPressedState.BorderRadius = 1;
            this.bunifuButtonCompany.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonCompany.OnPressedState.BorderThickness = 1;
            this.bunifuButtonCompany.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCompany.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCompany.OnPressedState.IconLeftImage = null;
            this.bunifuButtonCompany.OnPressedState.IconRightImage = null;
            this.bunifuButtonCompany.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonCompany.TabIndex = 5;
            this.bunifuButtonCompany.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonCompany.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonCompany.TextMarginLeft = 0;
            this.bunifuButtonCompany.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonCompany.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(17)))), ((int)(((byte)(23)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 611);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(225, 50);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // bunifuButtonDashboard
            // 
            this.bunifuButtonDashboard.AllowAnimations = true;
            this.bunifuButtonDashboard.AllowMouseEffects = true;
            this.bunifuButtonDashboard.AllowToggling = false;
            this.bunifuButtonDashboard.AnimationSpeed = 200;
            this.bunifuButtonDashboard.AutoGenerateColors = false;
            this.bunifuButtonDashboard.AutoRoundBorders = false;
            this.bunifuButtonDashboard.AutoSizeLeftIcon = true;
            this.bunifuButtonDashboard.AutoSizeRightIcon = true;
            this.bunifuButtonDashboard.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDashboard.BackgroundImage")));
            this.bunifuButtonDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonDashboard.ButtonText = "Dashboard";
            this.bunifuButtonDashboard.ButtonTextMarginLeft = 0;
            this.bunifuButtonDashboard.ColorContrastOnClick = 45;
            this.bunifuButtonDashboard.ColorContrastOnHover = 45;
            this.bunifuButtonDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButtonDashboard.CustomizableEdges = borderEdges7;
            this.bunifuButtonDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonDashboard.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuButtonDashboard.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDashboard.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 0, 3);
            this.bunifuButtonDashboard.IconMarginLeft = 11;
            this.bunifuButtonDashboard.IconPadding = 5;
            this.bunifuButtonDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDashboard.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDashboard.IconSize = 30;
            this.bunifuButtonDashboard.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.IdleBorderRadius = 1;
            this.bunifuButtonDashboard.IdleBorderThickness = 1;
            this.bunifuButtonDashboard.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDashboard.IdleIconLeftImage")));
            this.bunifuButtonDashboard.IdleIconRightImage = null;
            this.bunifuButtonDashboard.IndicateFocus = false;
            this.bunifuButtonDashboard.Location = new System.Drawing.Point(5, 140);
            this.bunifuButtonDashboard.Margin = new System.Windows.Forms.Padding(5);
            this.bunifuButtonDashboard.Name = "bunifuButtonDashboard";
            this.bunifuButtonDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDashboard.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonDashboard.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDashboard.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDashboard.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDashboard.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButtonDashboard.onHoverState.BorderRadius = 1;
            this.bunifuButtonDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonDashboard.onHoverState.BorderThickness = 1;
            this.bunifuButtonDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDashboard.onHoverState.IconLeftImage = null;
            this.bunifuButtonDashboard.onHoverState.IconRightImage = null;
            this.bunifuButtonDashboard.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.OnIdleState.BorderRadius = 1;
            this.bunifuButtonDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonDashboard.OnIdleState.BorderThickness = 1;
            this.bunifuButtonDashboard.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDashboard.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDashboard.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDashboard.OnIdleState.IconLeftImage")));
            this.bunifuButtonDashboard.OnIdleState.IconRightImage = null;
            this.bunifuButtonDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDashboard.OnPressedState.BorderRadius = 1;
            this.bunifuButtonDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonDashboard.OnPressedState.BorderThickness = 1;
            this.bunifuButtonDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDashboard.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDashboard.OnPressedState.IconRightImage = null;
            this.bunifuButtonDashboard.Size = new System.Drawing.Size(215, 30);
            this.bunifuButtonDashboard.TabIndex = 4;
            this.bunifuButtonDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDashboard.TextMarginLeft = 0;
            this.bunifuButtonDashboard.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.bunifuButtonDashboard.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Rockwell Condensed", 15F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bunifuLabel2.Location = new System.Drawing.Point(119, 40);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(89, 25);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "SUPPLIERS";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Rockwell Condensed", 15F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bunifuLabel1.Location = new System.Drawing.Point(100, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(58, 25);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "RAJANI";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(10, 8);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(70, 63);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1284, 661);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonStock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonSettings;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonInvoices;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonProducts;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonCompany;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonDashboard;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}